name: CI

on:
  push:
    branches:
    - main
    - dev
    paths:
    - '!**.md'
  pull_request:
    branches:
    - main
    - dev
    paths:
    - '!**.md'

jobs:
  prerequisites:
    uses: ./.github/workflows/test.yml
